---
parser: "@typescript-eslint/parser"
parserOptions:
  allowImportExportEverywhere: false
plugins:
  - "meteor"
  - "tsdoc"
  - "@typescript-eslint"
extends:
  - "airbnb"
  - "plugin:meteor/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
settings:
  "import/resolver":
    meteor:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
    typescript:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
rules:
  # noImplicitReturns requires us to declare return types, so TypeScript will
  # already warn if we fail to return a value, and it can tell when an explicit
  # return is unnecessary (e.g. if a function narrows a type to never)
  "consistent-return": ["off"]
  "default-case": ["off"]

  "no-underscore-dangle":
    - "error"
    - "allow":
      - "_id"

  "import/extensions": ["error", "never"]

  # Imports should be grouped, and sorted within the group. Meteor imports
  # are their own group, after built-ins and before other external libraries
  "import/order":
    - "error"
    - "alphabetize": {"order": "asc"}
      "pathGroups":
        - "pattern": "meteor/**"
          "group": "external"
          "position": "before"
      "pathGroupsExcludedImportTypes": ["builtin"]
      "newlines-between": "never"

  "tsdoc/syntax": ["error"]

  # This is an idealistic rule that doesn't seem to have ever encountered
  # reality
  "@typescript-eslint/no-explicit-any": ["off"]

  # Use underscore prefixes on arguments to indicate that they're unused
  "@typescript-eslint/no-unused-vars":
    - "error"
    - "argsIgnorePattern": "^_"

  "@typescript-eslint/no-namespace": ["off"]
overrides:
  - files: "types/**"
    rules:
      # type declarations for other libraries don't get to choose their export
      # structure
      "import/prefer-default-export": ["off"]
  - files: "tests/**"
    rules:
      # arrow functions with mocha are discouraged
      func-names: ["off"]
      prefer-arrow-callback: ["off"]

      # tests can make unsafe assumptions we don't want in real code
      "@typescript-eslint/no-non-null-assertion": ["off"]
